main: cf.dirt.instance.Plugin
name: Instance
version: 1.0.5
api-version: 1.14
description: Provides standard tools and configuration for an instance at dirt.cf
author: kubachrabanski

commands:
  memory:
    description: "Shows memory statistics"
    usage: "Usage: /<command>"
    permission: instance.command.memory
  processor:
    description: "Shows processor statistics"
    usage: "Usage: /<command>"
    permission: instance.command.processor

permissions:
  instance.command.memory:
    default: op
  instance.command.processor:
    default: op
  instance.command.message:
    default: true